# Generated by Django 4.2.7 on 2023-11-10 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('estrato', models.IntegerField()),
                ('cantidadDeHabitantes', models.IntegerField()),
                ('cantidadDeBaños', models.IntegerField()),
                ('cantidadDeParqueaderos', models.IntegerField()),
                ('piso', models.IntegerField()),
                ('antiguedad', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('areaPrivada', models.IntegerField()),
                ('areaConstruida', models.IntegerField()),
                ('precioAdministracion', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('direccion', models.CharField(max_length=300)),
                ('caracteristicas', models.ManyToManyField(related_name='caracteristicas', to='inmobiliaria.caracteristica')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeCaracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('edad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InmueblePorUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.FloatField()),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.inmueble')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='inmueble',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.sector'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='tipoDeInmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.tipodeinmueble'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.pais'),
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='tipoDeCaracteristica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.tipodecaracteristica'),
        ),
    ]
