# Generated by Django 4.2.7 on 2024-06-23 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('edad', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeCaracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InteresPorUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.interes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=600, null=True)),
                ('estrato', models.IntegerField(null=True)),
                ('cantidadDeHabitaciones', models.IntegerField(null=True)),
                ('cantidadDeBaños', models.IntegerField(null=True)),
                ('cantidadDeParqueaderos', models.IntegerField(null=True)),
                ('antiguedad', models.CharField(max_length=200, null=True)),
                ('precioM2', models.CharField(max_length=200, null=True)),
                ('valorArriendo', models.FloatField(null=True)),
                ('url', models.CharField(max_length=200, unique=True)),
                ('areaPrivada', models.CharField(max_length=200, null=True)),
                ('areaConstruida', models.CharField(max_length=200, null=True)),
                ('precioAdministracion', models.FloatField(null=True)),
                ('precio', models.FloatField(null=True)),
                ('estado', models.CharField(max_length=200, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('caracteristicas', models.ManyToManyField(blank=True, related_name='caracteristicas', to='inmobiliaria.caracteristica')),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.ciudad')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.sector')),
                ('tipoDeInmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.tipodeinmueble')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.pais')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.departamento'),
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='tipoDeCaracteristica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.tipodecaracteristica'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='intereses',
            field=models.ManyToManyField(blank=True, related_name='intereses', through='inmobiliaria.InteresPorUsuario', to='inmobiliaria.interes'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='InmueblePorUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.FloatField(null=True)),
                ('numeroDeClicks', models.BigIntegerField(null=True)),
                ('favorito', models.BooleanField(null=True)),
                ('comentarios', models.CharField(max_length=600, null=True)),
                ('calificacion', models.IntegerField(null=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.inmueble')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'inmueble')},
            },
        ),
    ]
