# Generated by Django 4.2.7 on 2024-04-07 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inmobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=600, null=True)),
                ('estrato', models.CharField(max_length=200, null=True)),
                ('cantidadDeHabitaciones', models.IntegerField(null=True)),
                ('cantidadDeBaños', models.IntegerField(null=True)),
                ('cantidadDeParqueaderos', models.CharField(max_length=200, null=True)),
                ('piso', models.CharField(max_length=150, null=True)),
                ('antiguedad', models.CharField(max_length=200, null=True)),
                ('precioM2', models.FloatField(null=True)),
                ('url', models.CharField(max_length=200, unique=True)),
                ('areaPrivada', models.CharField(max_length=200, null=True)),
                ('areaConstruida', models.CharField(max_length=200, null=True)),
                ('precioAdministracion', models.IntegerField(null=True)),
                ('precio', models.FloatField(null=True)),
                ('estado', models.CharField(max_length=200, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('caracteristicas', models.ManyToManyField(blank=True, related_name='caracteristicas', to='inmobiliaria.caracteristica')),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeCaracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('role', models.CharField(max_length=255, null=True)),
                ('edad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InmueblePorUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.FloatField(null=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.inmueble')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='inmueble',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.sector'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='tipoDeInmueble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.tipodeinmueble'),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.pais')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.departamento'),
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='tipoDeCaracteristica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.tipodecaracteristica'),
        ),
    ]
