# Generated by Django 4.2.7 on 2023-11-10 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='cantidadDeHabitantes',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='cantidadDeHabitaciones',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='antiguedad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='areaConstruida',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='areaPrivada',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='cantidadDeBaños',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='cantidadDeParqueaderos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.ciudad'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='direccion',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='estado',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='estrato',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='piso',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precioAdministracion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.sector'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
