# Generated by Django 4.2.7 on 2024-04-07 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0004_usuario_groups_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuario',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='role',
        ),
    ]
