# Generated by Django 4.2.7 on 2023-11-11 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0005_alter_inmueble_estado_alter_inmueble_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='tipoDeInmueble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.tipodeinmueble'),
        ),
    ]
