# Generated by Django 4.2.7 on 2023-11-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0006_alter_inmueble_tipodeinmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombreDeUsuario',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
