# Generated by Django 4.2.7 on 2024-04-08 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0006_alter_caracteristica_nombre_alter_ciudad_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='precioAdministracion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precioM2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipoDeInmueble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.tipodeinmueble'),
        ),
    ]
