# Generated by Django 4.2.7 on 2023-11-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0007_usuario_nombredeusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmuebleporusuario',
            name='clasificacion',
            field=models.FloatField(null=True),
        ),
    ]
