# Generated by Django 4.2.7 on 2024-04-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0015_alter_inmueble_tipodeinmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmuebleporusuario',
            name='numeroDeClicks',
            field=models.BigIntegerField(null=True),
        ),
    ]
