# Generated by Django 4.2.7 on 2024-04-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0016_inmuebleporusuario_numerodeclicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='clasificacion',
            field=models.IntegerField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='comentarios',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inmuebleporusuario',
            name='favorito',
            field=models.BooleanField(null=True),
        ),
    ]
