# Generated by Django 4.2.7 on 2024-04-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0017_inmueble_clasificacion_inmueble_comentarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='clasificacion',
            field=models.IntegerField(null=True),
        ),
    ]
