# Generated by Django 4.2.7 on 2024-04-26 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0018_alter_inmueble_clasificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='clasificacion',
            new_name='calificacion',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='piso',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='valorArriendo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='cantidadDeParqueaderos',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='InteresPorUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.interes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
