# Generated by Django 4.2.7 on 2024-05-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0019_interes_rename_clasificacion_inmueble_calificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='intereses',
            field=models.ManyToManyField(blank=True, related_name='intereses', to='inmobiliaria.interes'),
        ),
    ]
