# Generated by Django 4.2.7 on 2024-05-07 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0022_alter_ciudad_nombre_alter_departamento_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.departamento'),
        ),
    ]
