# Generated by Django 4.2.7 on 2024-05-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0023_alter_ciudad_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='estrato',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precioAdministracion',
            field=models.FloatField(null=True),
        ),
    ]
